language: php

# keep verisions minimal to limit total
# builds on free service. politeness.
php:
    - "5.5"

services:
    - mysql

sudo: false

branches:
    only:
        - master

addons:
    code_climate:
        repo_token: 67366d8ac65880a3f66c348459e1cfee12a1c48cbf79ed53169348623748c50e

# test both msyqli and PDO 
env:
    matrix:
        - DB_DRIVER=pdo_mysql
        - DB_DRIVER=mysqli

install:
    - sh tests/pos/travis-init.sh
    - composer install
    - mkdir -p build/logs
    - npm install acorn

script:
    - phpunit -d max_execution_time=0 -c phpunit.xml
    - sh tests/acorn.sh

after_script:
    - vendor/bin/test-reporter

